### ISSUE TITLE
CLI shows an INFO log message

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/nmcontrol#102]
Previously when the CLI was used, only the result was printed.  Now for some reason the following is what I get:

    $ ./nmcontrol.py dns getIp4 domob.bit
    2015-09-08 19:53:35,215 - __main__ - INFO - ###################################################################################
    ["176.31.184.255"]

The INFO message is distracting, useless, and may adversely affect applications that parse NMControl's CLI output.  (Of course, applications should probably be using RPC or REST for that, but it's still a bug.)

**Comment by phelixbtc** [comment]
Thanks for catching this. It would also clear the log file on each command line call. ::)
