### ISSUE TITLE
Insufficient installation guide for Windows

### ISSUE THREAD

**Issue by slrslr** [namecoin/nmcontrol#120]
At https://bit.namecoin.org/browse.html you say NMControl is for browsing .bit sites so i followed link you provided on that page and i ended up in this github project. README says for to execute following in case of a Windows OS:

pip install pywin32

> Collecting pywin32
>   Could not find a version that satisfies the requirement pywin32 (from versions: )
> No matching distribution found for pywin32
> 

have pip-9.0.1

tried: pip install pypiwin32
succeeded

bottle installed too

python nmcontrolwin.pyw

> python: can't open file 'nmcontrolwin.pyw': [Errno 2] No such file or directory

So there were 2 problems with installation guide mentioned in README.md
Third problem is that is not mentioned how noob can install python, no link to a tutorial. some tutorial [is here](https://internetlifeforum.com/computers-technology/8159-guide-how-install-python-windows/).
Fourth problem is when i download this project .zip file extract it and run like: python "C:\Program Files\nmcontrol-master\nmcontrolwin.pyw"

window with following error appears:
> Traceback, File "...\nmcontrolwin.pyw" line 9, in <module> import splashscreen
ModuleNotFoundError: No module named 'splashscreen'

It would be nice if your README is made the way so i know how to install the software without errors like four errors above, more detailed, and what to exactly do.
Is there any missing steps in Windows installation tutorial?

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

slrslr:
> At https://bit.namecoin.org/browse.html you say NMControl is for
> browsing .bit sites so i followed link you provided on that page
> and i ended up in this github project. README says for windows to
> execute:

[snip]

> It would be nice if your README is made the way so i know how to
> install the software without errors like one above. Also it do not
> contains any information on how to install python. Not everyone is
> a programmer to know how to do it. More noob friendly guide for
> Windows would be good.

Hello!  NMControl is currently being phased out in favor of ncdns.
You can download a beta Windows installer for ncdns at
https://www.namecoin.org/download/betas/ .  Let us know if any issues
arise with it.

Cheers.


-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJZXQ/JAAoJELPy0WV4bWVwVAQP/2yqGr+5KF1LjpZCEY2OYF9d
Bm5ydiIL0rgkxXlffqwlb7GKFjbQaK/5luyt2rsEJhU0dk1SiFse/zGjawew1Wk0
I5HTfgtgg6qRQFPUAJ9B7rzTFUKybsECfHbYVdnruflYDLvZI/vu0bdKz1a14n1w
ATsaXwKp4BuS3lB4Kk/0ABPMk6jz00WA3Qkt7oqyFb0U2+HtXyTXnCSOsdFskhkm
pvzgRnzl05RRW+bEi/eIJcj4D+rtW7l9XhH2vY57OQCkpt0OdV9LrLNlHGu3/PRE
aJ+Mw0cW9egpem/xAyUJMIXu6x3IJygi/7D/aSCRSRofbMol5AwfTqhFnGrLNvz2
OZbPYijN58/wr6BsHdpH0NQKbp5XEXRd3TX2/EuIi76KxMVs2UpNwWJbThdYNiyR
EQ+xdwMQISPrfPym11TbiK9vXfP+gxy4wGFdx8qobYPdIVsjHl/re7qk+bvQpmBB
YaMhe7+v6zr91wsOUYoYI7yhbyruW/e1bgcuLfXzVswvTHgFPhb2Au0fgQU8cuhQ
OOCyvfBuklCZXpqnBw7avEa0xuu7IAWenps7wPRjnl3maNnc0nI95brXoz+JoNLe
NIKWbY9M7ZS03Z8mDztCS4oRsJlOK7DP1j2LS6sbgBdNkN3tXO4SgfNoir83YHpF
fat5caZ8TFeHGfGsRAcY
=Cm+M
-----END PGP SIGNATURE-----
