### ISSUE TITLE
Plugin Management

### ISSUE THREAD

**Issue by indolering** [namecoin/nmcontrol#56]
Forgive my ignorance of previous discussions, but shouldn't the plugins be modularized away from the core repo?  This occurred to me while working on a post about development vs stable branches and I don't think that major changes to a plugin shouldn't require breaking the main repo or switching branches. 

I'm not sure what the right level of abstraction is, perhaps there should be a repo with default plugins that is a submodule to namecoin/nmcontrol.  Since we have mainly first-party plugins, we could just host them all right there.  However, I think each plugin should have it's own directory and perhaps a setup.py file for version info.
  
I'm not sure if we should have external plugins register with PyPi yet, I don't think that there are enough of them.  We could just have a list of links on the main NMControl repo readme.md.  Once that get's unwieldy, we could switch to PyPi.....

**Comment by JeremyRand** [comment]
So, in principle I wouldn't really have a huge objection to having the plugins be in independent GitHub repos.  However, I don't see much practical benefit either.  Are you looking at the use case of someone who needs unreleased/bleeding-edge versions of a subset of plugins, but stable versions of other plugins?  That seems like a use case that's rare and probably knows how to use Git to get what they want anyway.  I don't see any other use cases for this.

**Comment by phelixbtc** [comment]
Most current plugins are only technically plugins, I would call them core plugins. Maybe for new optional large plugins but IMHO even then it may be too early as it complicates packaging etc.

**Comment by phelixbtc** [comment]
About to close.

**Comment by JeremyRand** [comment]
@phelixbtc I'm okay with closing.  We can re-file a ticket when this becomes more relevant.
