### ISSUE TITLE
Dev Branch Seems Branched From Wrong Parent

### ISSUE THREAD

**Issue by phelixbtc** [namecoin/nmcontrol#57]
It is more than 10 commits different, e.g. it has the anonymous contributions removed.

**Comment by JeremyRand** [comment]
@phelixbtc That is intentional.  The anonymous contributions are all related to the old DNS code that's being rewritten, therefore by rewriting the DNS code (which we were going to do anyway) we get to remove those commits for free.

**Comment by phelixbtc** [comment]
OK
