### ISSUE TITLE
Error upon startup: missing directory

### ISSUE THREAD

**Issue by unsystemizer** [namecoin/nmcontrol#98]
![image](https://cloud.githubusercontent.com/assets/13134193/9651638/d4980816-5245-11e5-91c0-bb650814d761.png)

v0.8

Workaround: manually create missing directory

**Comment by phelixbtc** [comment]
This is serious. Thanks for reporting.

**Comment by phelixbtc** [comment]
Fixed as of https://github.com/namecoin/nmcontrol/pull/101
